# docker-compose.yaml
version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}